package dev.gustavpersson.thorincompanies.business_logic_layer.enums

enum class ErrorCode {
    DB_INIT,
    DB_TABLE_GENERATION,
    COMPANY_START,
    UNEXPECTED,
    COMP_NAME_ALREADY_EXISTS,
    INSUFFICIENT_FUNDS_TO_START_COMP,
    MAX_COMPANIES_REACHED,
    ONLY_FOUNDER_CAN_DELETE,
    CONFIG_PROPERTY_NOT_FOUND,
    CONFIG_PROPERTY_WRONG_TYPE,
    MESSAGE_PROPERTY_NOT_FOUND,
    COMP_NAME_NOT_SPECIFIED,
    COMP_NAME_NOT_FOUND
}