name: ThorinCompanies
version: '${project.version}'
main: dev.gustavpersson.thorincompanies.ThorinCompanies
api-version: 1.18
authors: [ ThorinEk ]
description: Minecraft Companies plugin developed by ThorinEk.
website: https://gustavpersson.dev/

depend: [Vault]
softdepend:
  - QickShop

commands:
  com:
    description: Main command
